version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=invent_analytics_case_user
      - DB_PASSWORD=1234@Ahmet
      - DB_DATABASE=invent_analytics_db
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - library_case
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - DB_USERNAME=invent_analytics_case_user
      - DB_PASSWORD=1234@Ahmet
      - DB_DATABASE=invent_analytics_db
    networks:
      - library_case

networks:
  library_case:

