--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8 (Homebrew)
-- Dumped by pg_dump version 16.4

-- Started on 2024-09-20 13:33:29 +03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 24579)
-- Name: books; Type: TABLE; Schema: public; Owner: invent_analytics_case_user
--

CREATE TABLE public.books (
    id integer NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    score integer
);


ALTER TABLE public.books OWNER TO invent_analytics_case_user;

--
-- TOC entry 214 (class 1259 OID 24578)
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: invent_analytics_case_user
--

CREATE SEQUENCE public.books_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.books_id_seq OWNER TO invent_analytics_case_user;

--
-- TOC entry 3677 (class 0 OID 0)
-- Dependencies: 214
-- Name: books_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: invent_analytics_case_user
--

ALTER SEQUENCE public.books_id_seq OWNED BY public.books.id;


--
-- TOC entry 217 (class 1259 OID 24589)
-- Name: borrowed_books; Type: TABLE; Schema: public; Owner: invent_analytics_case_user
--

CREATE TABLE public.borrowed_books (
    id integer NOT NULL,
    "bookId" integer NOT NULL,
    "userId" integer NOT NULL,
    score integer,
    "isReturned" boolean DEFAULT false NOT NULL
);


ALTER TABLE public.borrowed_books OWNER TO invent_analytics_case_user;

--
-- TOC entry 216 (class 1259 OID 24588)
-- Name: borrowed_books_id_seq; Type: SEQUENCE; Schema: public; Owner: invent_analytics_case_user
--

CREATE SEQUENCE public.borrowed_books_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.borrowed_books_id_seq OWNER TO invent_analytics_case_user;

--
-- TOC entry 3678 (class 0 OID 0)
-- Dependencies: 216
-- Name: borrowed_books_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: invent_analytics_case_user
--

ALTER SEQUENCE public.borrowed_books_id_seq OWNED BY public.borrowed_books.id;


--
-- TOC entry 219 (class 1259 OID 24597)
-- Name: users; Type: TABLE; Schema: public; Owner: invent_analytics_case_user
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name character varying(255) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public.users OWNER TO invent_analytics_case_user;

--
-- TOC entry 218 (class 1259 OID 24596)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: invent_analytics_case_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3517 (class 2604 OID 24582)
-- Name: books id; Type: DEFAULT; Schema: public; Owner: invent_analytics_case_user
--

ALTER TABLE ONLY public.books ALTER COLUMN id SET DEFAULT nextval('public.books_id_seq'::regclass);


--
-- TOC entry 3519 (class 2604 OID 24592)
-- Name: borrowed_books id; Type: DEFAULT; Schema: public; Owner: invent_analytics_case_user
--

ALTER TABLE ONLY public.borrowed_books ALTER COLUMN id SET DEFAULT nextval('public.borrowed_books_id_seq'::regclass);


--
-- TOC entry 3525 (class 2606 OID 24595)
-- Name: borrowed_books PK_01047184a37de804d08725858ba; Type: CONSTRAINT; Schema: public; Owner: invent_analytics_case_user
--

ALTER TABLE ONLY public.borrowed_books
    ADD CONSTRAINT "PK_01047184a37de804d08725858ba" PRIMARY KEY (id);


--
-- TOC entry 3527 (class 2606 OID 24602)
-- Name: users PK_a3ffb1c0c8416b9fc6f907b7433; Type: CONSTRAINT; Schema: public; Owner: invent_analytics_case_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY (id);


--
-- TOC entry 3523 (class 2606 OID 24587)
-- Name: books PK_f3f2f25a099d24e12545b70b022; Type: CONSTRAINT; Schema: public; Owner: invent_analytics_case_user
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT "PK_f3f2f25a099d24e12545b70b022" PRIMARY KEY (id);


--
-- TOC entry 3528 (class 2606 OID 24608)
-- Name: borrowed_books FK_408f82dab16da2fa7631a61e8f6; Type: FK CONSTRAINT; Schema: public; Owner: invent_analytics_case_user
--

ALTER TABLE ONLY public.borrowed_books
    ADD CONSTRAINT "FK_408f82dab16da2fa7631a61e8f6" FOREIGN KEY ("userId") REFERENCES public.users(id);


--
-- TOC entry 3529 (class 2606 OID 24603)
-- Name: borrowed_books FK_6ee8aef29eec0a9aac3b5e288c3; Type: FK CONSTRAINT; Schema: public; Owner: invent_analytics_case_user
--

ALTER TABLE ONLY public.borrowed_books
    ADD CONSTRAINT "FK_6ee8aef29eec0a9aac3b5e288c3" FOREIGN KEY ("bookId") REFERENCES public.books(id);


-- Completed on 2024-09-20 13:33:30 +03

--
-- PostgreSQL database dump complete
--

